import type { Metadata } from "next";
import { Geist, Geist_Mono,  Oswald } from "next/font/google";
import "./globals.css";
import {NextFontWithVariable} from "next/dist/compiled/@next/font";

const geistSans: NextFontWithVariable = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const oswald = Oswald({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],  // include only the weights you need
    display: "swap",
    variable: "--font-oswald",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${oswald.className} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
